### PR TITLE
Update .codeclimate.yml

### PR DESCRIPTION
**Pull request by wattsecs**
Set the threshold of similar lines codeclimate considers to 3

### CODE REVIEW

**Review by NicolasVial — APPROVED** [review]
I think 3 lines is a good choice for the moment.

**Comment by bbjubjub2494** [comment]
This causes 82 issues to pop up in CodeClimate. the unit of measurement for identical and similar code isn't number of lines, it's [number of AST nodes](https://docs.codeclimate.com/docs/duplication-concept). You need to increase that

**Comment by wattsecs** [comment]
> 
> 
> This causes 82 issues to pop up in CodeClimate. the unit of measurement for identical and similar code isn't number of lines, it's [number of AST nodes](https://docs.codeclimate.com/docs/duplication-concept). You need to increase that

True, sorry about that. I could not find how to set those correctly.
Maybe keeping .codeclimate.yml as it was and marking the codeclimate issues as resolved manually on a case by case basis would be better.

**Comment by bbjubjub2494** [comment]
> Maybe keeping .codeclimate.yml as it was and marking the codeclimate issues as resolved manually on a case by case basis would be better.

I agree. Do you want to close this?

**Comment by wattsecs** [comment]
> 
> 
> > Maybe keeping .codeclimate.yml as it was and marking the codeclimate issues as resolved manually on a case by case basis would be better.
> 
> I agree. Do you want to close this?

Yes

**Pull request closed without merging**
