### PR TITLE
Feature/75 refactor activities fragments

### PR DESCRIPTION
**Pull request by martin-lenweiter**
-Will be merged last as it touches all it touches all parts of the UI.

-I didn't manage to transform AddPictureActivity to a fragment. I think I'll wait to merge Louis' changes from this week before trying further.

### CODE REVIEW

**Comment by bbjubjub2494** [comment]
Wait I edited the OP last evening? I meant to reply!

**Comment by bbjubjub2494** [comment]
> -I can't manage to launch the tests for Learning, it crashes without an error message. If anyone knows what this can be let me know! But it behaves as it did before.

This should be fixed in master now that #103 is merged

**Comment by wattsecs** [comment]
Please address codeClimate concerns and merge conflicts

**Comment by martin-lenweiter** [comment]
> Please address codeClimate concerns and merge conflicts

codeClimate: done

merge conflicts: will have to be done manually and carefully once all the other PR's have been merged.

**Pull request closed without merging**
