### PR TITLE
Add Dependency injection

### PR DESCRIPTION
**Pull request by bbjubjub2494**
- [x] find a way to test fragments
- [x] fix tests that broke

Configured Hilt to pass the same components to different activities where necessary. Tests still run in isolation.

### CODE REVIEW

**Comment by bbjubjub2494** [comment]
[Hilt cannot be used in vanilla JVM tests](https://dagger.dev/hilt/testing)

**Comment by bbjubjub2494** [comment]
need #84

**Review by Nitwix — APPROVED** [review]
Perfect! I hope it can be merged soon so that I can use hilt in my tests for this sprint.

**Review by wattsecs — APPROVED** [review]
Didn't find anything to add. Good work adapting everything.

**Pull request merged**
