### PR TITLE
Add Code Climate badges to README

### PR DESCRIPTION
**Pull request by Nitwix**

### CODE REVIEW

**Review by bbjubjub2494 — APPROVED** [review]
please rebase but otherwise :white_check_mark:

**Comment by Nitwix** [comment]
> please rebase but otherwise white_check_mark

Sorry for asking, but could you explain please? I'm not really comfortable with advanced git functionnality

**Comment by bbjubjub2494** [comment]
Sure thing.

Right now, the commit graph looks like this
```
*   05094fb (housekeeping/badges) Merge branch 'main' into housekeeping/badges
|\  
| *   3feadbd (main) Merge pull request #25 from HumanLearning2021/bugfix/AddPictureActivityTest
| |\  
| | * 604179b change how the tests grant the permission for the camera to improve reliability on cirrus ci
| |/  
* / afa07fa Add Code Climate badges to README
|/  
*   6b0a034 Merge pull request #19 from HumanLearning2021/summaries
```

This is undesirable because there's a merge commit cluttering the view. Instead I would like to make it look like this:
```
* xxxxxxx (housekeeping/badges) Add Code Climate badges to README
*   3feadbd (main) Merge pull request #25 from HumanLearning2021/bugfix/AddPictureActivityTest
|\  
| * 604179b change how the tests grant the permission for the camera to improve reliability on cirrus ci
|/  
*   6b0a034 Merge pull request #19 from HumanLearning2021/summaries
```
The contents should remain the same, but the history is cleaner. In this case, this result can be achieved just by running `git rebase main` if you use the command-line. It will replay your changes on top of the current main branch, toss the merge commit and produce the result above. (Feel free to check the [manual](https://git-scm.com/docs/git-rebase) for more details)

A more advanced usage of rebase is to reorder, reword, or combine commits using the `--interactive` option. In fact you might need to do that in the other PR. This is essential to end up with good commit messages per SwEng guidelines. Also, rewriting history is a powerful tool that so the rule is: don't rewrite other people's branches without permission, and never `main`. Also if you screw up, your old commits can be found in `git reflog`

**Comment by Nitwix** [comment]
Thanks a lot for the explanation @lourkeur, I'll try to rebase

**Review by wattsecs — APPROVED** [review]
Looks good to me

**Pull request merged**
